@extends('layout.base_layout')
@section('titulo')
  {{'WGames - Home'}}
@stop

@section('conteudo')
      <h2>História Dos Jogos:</h2>
      <p>A história dos jogos  eletrônicos envolve o desenvolvimento dos jogos, que começaram a  ser populares na década de 1970 - inicialmente em computadores - e  logo culminaram na criação dearcades e consoles de videogames.      </p>
<p>1958      </p>
<p>O primeiro jogo para  computadores foi criado no Estados Unidos, mais exatamente no  laboratório de pesquisas militares Brookhaven National Laboratory. O  programa se chamava Tennis for Twoe era exibido na tela de um  osciloscópio. Uma simulação bem simplificada do esporte. Um ponto  piscando representava a bola e os jogadores controlavam seu movimento  por cima de uma linha vertical que representava a rede. Não havia na  imagem a representação dos jogadores, apenas da 'bola' e da  'quadra' de tênis, numa vista lateral. O jogo nunca saiu do  laboratório.      </p>
      <p>Em 1958 o físico  William Higinbotham que havia trabalhado na primeira bomba atômica  transformou duas linhas rudimentares e uma bola na primeira  experiência interativa de entretenimento em computador: Maatooka.</p>
      <p>1961 </p>
<p>Em 30 de julho de 1961,  um grupo de estudantes do Massachusetts Institute of Technology (MIT)  testava pela primeira vez Spacewar!, um jogo eletrônico desenvolvido  em um enorme computador que custava milhares de dólares.      </p>
      <p>Tendo o grosso de seu  programa feito por Steve &quot;Slug&quot; Russell, com o auxílio de  seus colegas Dan Edwards, Alan Kotok, Peter Sampson e Martin Graetz,  esses auto-proclamados precursores dos 'geeks' (&quot;nerds&quot;  viciados em informatica) se inspiraram nos livros do autor E. E.  &quot;Doc&quot; Smith para criar seu jogo de batalha espacial.      </p>
<p>O programa foi  inteiramente desenvolvido no DEC PDP-1, um antigo computador que  ocupava uma mesa inteira. Os criadores de Spacewar não pensavam em  ganhar dinheiro com a invenção, já que não havia mercado, pois na  época não existiam ainda os computadores domésticos.      </p>
      <p>Na verdade, tudo  começou como um desafio para Russell: com o novo computador dotado  de transistores ao invés de válvulas e uma tela (peças de luxo na  época), o TX-0, conhecido como Tixo, eles decidiram fazer o que  ninguém mais fez por eles: transpor a ficção científica da  literatura para uma outra mídia.      </p>
<p>O TX-0 acabou sendo  abandonado pelo PDP-1, recém-adquirido pela faculdade. Ainda mais  rápido que o TX-0 e igualmente programável, ele era o sonho dos  garotos. E poderia ser ligado instantâneamente, ao contrário de seu  predecessor, que precisava de uma manhã inteira para aquecimento  interno. Eles queriam criar algum tipo de demonstração, e por isso  criaram algumas regras que seu programa deveria seguir:      </p>
      <p>Deveria demonstrar as  capacidades do computador, usando quase todo seu potencial      </p>
      <p>Deveria ser  interessante e interativo (diferente toda vez que rodado)      </p>
<p>Deveria envolver o  usuário de maneira atrativa e prazerosa - ou seja, deveria ser um  jogo      </p>
      <p>Os jovens então  criaram duas naves, uma rotina para simular inércia e um campo  estelar aleatório para ajudar a controlar o movimento. Eles queriam  também adicionar um &quot;botão de pânico para emergências&quot;,  e assim nasceu a tecla Hiper-Espaço. O último toque seria a estrela  no meio do campo de batalha, que gerava um campo gravitacional que  poderia tanto atrapalhar ou ajudar, dependendo da astúcia do  jogador.      </p>
<p>Spacewar só estaria  oficialmente finalizado em 1962, ocupando apenas 2KB. Russell jamais  ganharia um dólar pelo jogo - mas isso não quer dizer que outros  não lucrariam com ele.      </p>
<p>Década de 1970      </p>
<p>1971      </p>
<p>Em 1966, o engenheiro  Ralph Baer foi incumbido de criar a melhor televisão do mundo. Ele  pensava em criar uma TV interativa com jogos, mas a ideia não  vingou. Anos mais tarde, em 1971, aMagnavox compra o projeto de Baer,  da Sanders Associates, e começa a desenvolver o Odyssey 100, o  primeiro videogame para ser conectado à TV.      </p>
<p>Enquanto isso, Nolan  Bushnell, tranforma o quarto da filha numa oficina e adapta o jogo  Spacewar!, de Steve Russell, criando Computer Space, o primeiro  arcade do mundo. Como os mainframes eram muito caros e ocupavam muito  espaço, Bushnell criou a Computer Space, uma máquina só para jogar  Spacewar. A experiência dá certo e ele passa a vender a novidade.  ANutting Associates se interessa e contrata Bushnell,  temporariamente, para montar os arcades de Computer Space. Mais tarde  Bushnell sai da empresa para fundar a Atari.      </p>
<p>1973      </p>
<p>Pong, jogo para arcade  criado por Bushnell na Atari, se torna um fenômeno e várias  empresas, como a Ramtek e a Nutting, começam a lançar similares. A  Atari estabelece contato com a Namco do Japão.      </p>
<p>1974      </p>
<p>Executivos da Atari  vão, misteriosamente, para a rival Kee Games, em uma época em que  era necessário aumentar a distribuição de máquinas. A Kee Games  lança Tank, jogo mais vendido do ano, e ultrapassa a Atari em  vendas. Na verdade, a Kee Games era uma subdivisão da Atari (que  voltou ser uma empresa só com a Atari posteriormente) e, quando  voltaram ser uma única empresa, tranformaram-se em uma das maiores  indústrias de videogame de todos os tempos. Os funcionários da  Atari Harold Lee, Alcorn e o engenheiro Bob Brown desenvolvem uma  versão dePong para videogame, mas o interesse do público é pequeno  devido ao fracasso do Odyssey, uma caixa preta e branca com controles  tipo disco.      </p>
<p>1975      </p>
<p>A Atari entra em  contato com Tom Quinn, comprador de artigos esportivos da Sears  Roebuck, e apresenta-o ao jogo Pong. Após negociações, a Sears  compra 150.000 unidades do arcade(Arcade ou Fliperama, como é  tradicionalmente conhecidos no Brasil), muito mais do que a Atari  podia produzir. As máquinas vinham estampadas com o logo da Sears  Tele-Games. Bushnell consegue uma linha de crédito de 10 milhões de  dólares com Don Valentine para expandir a Atari. No Natal, o Home  Pong torna-se o campeão de vendas do catálogo da Sears.      </p>
<p>1976      </p>
<p>O sucesso da Atari leva  várias empresas a lançar consoles, mas somente a Coleco (abreviação  de Connecticut Leather Company) consegue aprontar tudo para o Dia dos  Pais. O videogameTelstar Pong usava tecnologia similar às das  máquinas de então.      </p>
<p>Enquanto isso, a  Fairchild Camera &amp; Instrument dá outro passo importante lançando  o Fairchild Channel F, o primeiro videogame programável. Congelar o  jogo, alterar o tempo e a velocidade passa a ser possível com  Fairchild Channel F. O joystick era bem interessante: o botão ficava  na ponta do manche e podia ser rotacionado. Assim, Pong ganhava  inclinação na &quot;raquete&quot; e podia rebater a bolinha em  vários ângulos.      </p>
<p>Nessa época, surgem as  primeiras críticas aos jogos eletrônicos violentos. Death Race, da  Exidy Games, foi o precursor de Carmaggedon. Sair atropelando tudo o  que viesse pela frente era o objetivo do jogo. Death Race serviu  ainda de inspiração para a criação de outro jogo recente,  Interstate 76.      </p>
<p>Com o mercado em  crescimento, Bushnell vende a Atari para a Warner, pois não vê  outra maneira de mantê-la competitiva.      </p>
<p>1977      </p>
<p>A Atari lança o Chuck  E. Cheese, uma combinação de casa de fliper com lanchonete, robôs,  jogos e cardápios familiares. Bushnell chama a franquia de Pizza  Time Theater.      </p>
<p>A Midway Games (que  lançou posteriormente jogos como: Gauntlet, Mortal Kombat, NBA Jam,  Rampage, Rush, Spy Hunter) lança o jogo Gunfight, o primeiro a usar  microprocessadores ao invés de um emaranhado de circuitos.  Desenvolvido pela Taito do Japão, Gunfight é o primeiro arcade a  ser importado pelos EUA.</p>
<p>Sob a liderança de  Bushnell, a Atari desenvolve o VCS (Video Computer System, mais tarde  chamado de Atari 2600) e lança-o no Natal por US$ 249,95 e em 1983  no Brasil.. Esse é o primeiro console programável com jogos em  cartucho da Atari. Entre os títulos, há conversões de jogos para  arcade e games criados exclusivamente para o console doméstico. As  vendas são um tremendo sucesso e, mesmo assim, acontecem atritos  entre Bushnell e Steve Ross, presidente da Warner Communications.</p>
      <p>1978<br />
    </p>
<p>A política da Atari de  não dar crédito às pessoas envolvidas na criação de jogos, mas  apenas para a própria empresa, faz com que surjam os primeiros  segredos em jogos (no Brasil, conhecidos como &quot;ovos de páscoa&quot;,  devido ao termo comum no inglês &quot;easter egg&quot;). Warren  Robinett, criador de Adventure, faz uma sala secreta onde seu nome  brilha em cores de arco-íris. Para entrar na sala, o jogador deveria  levar um ponto cinza para a tela inicial. Mais tarde, esses segredos  e truques se tornaram elementos obrigatórios nos games.</p>
<p>Bushnell deixa a Atari  e cria outra empresa. Um contrato de cinco anos, estipula que a Atari  não competirá com a nova empresa de seu ex-homem forte. A Pizza  Time Theaters também é comprada por Bushnell.</p>
<p>Ray Kassar chega à  presidência da Atari. Em março, a Nintendo (A Nintendo foi criada  por Fusajiro Yamauchi em 1889 e fabricava cartões artesanais de um  tipo de baralho tradicionalmentejaponês chamado Hanafuda) lança um  arcade chamado Computer Othello, uma versão do jogo de mesa Othello.  Não há joysticks, apenas 10 botões coloridos para cada jogador.  Cada partida custa 100 ienes (R$ 1,61), preço que virou padrão para  os jogos de arcade no Japão.</p>
<p>Dois lançamentos  aumentam, ainda mais, a popularidade dos games: Football da Atari e o  lendário Space Invaders, importado pela Midway Games e desenvolvido  pela Taito (Taito foi fundada 1953 é uma desenvolvedora de jogos  eletrônicos japonês pertencente à Square Enix desde 2005). Esses  dois títulos para arcade batem todos os recordes de vendas.</p>
<p>No Japão, a Namco (Namco foi fundada em Tokyo em 1955, por Masaya Nakamura com o nome: &quot;Nakamura Manufacturing Ltd&quot;) solta o Gee Bee, uma versão digital das mesas de fliper. Terminada a temporada de futebol americano, o jogo é esquecido. Mas Space Invaders continua sendo sucesso nos arcades e provoca até falta de moedas no mercado.</p>
      <h3>1979</h3>
      <p>Lunar Lander, o primeiro jogo comercial com gráficos vetoriais, na forma de wireframes, isto é, os objetos eram formados por linhas como se fossem o esqueleto de um modelo 3D, é lançado. Nasce então o antecessor dos gráficos poligonais, usados na maioria dos jogos da atualidade.</p>
      <p>Outro jogo lendário é o grande lançamento do ano: Asteroids. Apesar de ter vendido 80 mil cópias e de ter virado febre nos Estados Unidos, o jogo não fez muito sucesso em outros países.</p>
      <p>A Sega (A SEGA foi originalmente fundada em 1940 no Japão. SG1000 foi o primeiro video-game da Sega e foi um console da segunda geração de videogames lançado pela Sega em 1981 (versão de testes) e em 1983 (para o mercado).) solta o Monaco GP, base do Pro Monaco GP, de 1980, e do realista Super Monaco GP, de 1989.</p>
      <p>O sucesso do Atari 2600 prova que os videogames não são uma onda passageira. Conversões e jogos originais continuam a sair exclusivamente para o console, enquanto a empresa negocia os direitos de 'blockbusters' como Space Invaders.</p>
      <p>&nbsp;</p>
@stop  